accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),

    path('<pk>/comments/', views.comments_create, name='comments_create'),
    path('<movie_pk>/comments/<comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<pk>/likes/', views.likes, name='likes'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    description = models.TextField()

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_movies")

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    content = models.CharField(max_length=200)

    def __str__(self):
        return self.content
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    # 우리는 메타 클래스만 바꿔주면 된다
    class Meta(UserCreationForm.Meta):
        # 원래는 Auth.user지만
        # accounts.User를 보게 해주면 된다
        # 클래스를 직접 import해서 가져와도 되지만
        # user는 특별해서 장고에서 지원을 해주니까 저렇게 하자
        # 만약 내가 유저 모델을 세팅가서 바꾼다 하더라도 여기 굳이 다시 바꿔줄 필요X
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_safe, require_http_methods

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        # 비어있는 폼이 저기 form에 들어갈거
        form = CustomUserCreationForm()
    
    context = {'form': form,}
    return render(request, 'accounts/signup.html', context)


@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')

    else:
        # 기존 데이터 넣어주자 -> instance 활용
        form = CustomUserChangeForm(instance=request.user)
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)

    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

def profile(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호변경</h1>

  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="변경하기">
  </form>

  <a href="{% url 'movies:index' %}">목록보기</a>



{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ person.username }}님의 프로필</h1>
  <div>
    팔로잉 : {{ person.followings.count }} | 팔로워 : {{ person.followers.count }}
  </div>
  <form action="{% url 'accounts:follow' person.pk %}" method="POST">
    {% csrf_token %}  
    {% if request.user in person.followers.all %}
      <button type="submit" class="btn btn-danger">언팔로우</button>
    {% else %}
      <button type="submit" class="btn btn-success">팔로우</button>
    {% endif %}
  </form>
  <hr>

  <h5>{{ person.username }}님이 작성한 게시글</h5>
  {% for movie in person.movie_set.all %}
  <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ movie.title }}</h5>
        <p class="card-text">{{ movie.content }}</p>
        <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary">자세히 보기</a>
    </div>
  </div>
  {% endfor %}
  <hr><br><br>

  <h5>{{ person.username }}님이 작성한 댓글</h5>
  {% for comment in person.comment_set.all %}
  <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ comment.movie.title }}</h5>
        <p class="card-text">{{ comment.content }}</p>
        <a href="{% url 'movies:detail' comment.movie.pk %}" class="btn btn-primary">자세히 보기</a>
    </div>
  </div>
  {% endfor %}
  <hr><br><br>

  <h5>{{ person.username }}님이 좋아한 게시글</h5>
  {% for movie in person.like_movies.all %}
  <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ movie.title }}</h5>
        <p class="card-text">{{ movie.content }}</p>
        <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary">자세히 보기</a>
    </div>
  </div>
  {% endfor %}
  <hr><br><br>

  <a href="{% url 'movies:index' %}" class="btn btn-success">목록 보기</a>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>

  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="회원가입">
  </form>

  <a href="{% url 'movies:index' %}">목록보기</a>



{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원정보수정</h1>

  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="수정하기">
  </form>

  <a href="{% url 'movies:index' %}">목록보기</a>



{% endblock content %}